/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informatikb_system;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import oru.inf.InfDB;
import oru.inf.InfException;
import informatikb_system.Profile.*;
import java.awt.Color;

/**
 *
 * @author Reinis
 */
public class InlaggAdminGUI extends javax.swing.JFrame {
    private Profil_egen_visa MyProfile;

    /**
     * Creates new form Inlagg
     */
     
    private InlaggMgtAdmin inlagg;
    private InfDB idb;
    String amne;

    public InlaggAdminGUI() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        anslutDatabas();
    
        inlagg = new InlaggMgtAdmin();
        showSocInlagg("Socialt");
    }
    
    private void getSelectedTextOchDolj()
    {
        String titel = txtPaneSocialt.getSelectedText();
        doljInlagg(titel);
        
    }
    
    private void anslutDatabas()
    {
        try
        {
            String path = System.getProperty("user.dir"); //Hämtar user direcotry
            idb = new InfDB(path + "/databas/DATABASE.FDB"); 
            System.out.println("Uppkopplingen lyckades");
        }
        catch(InfException e)
        {
            System.out.println(e.getMessage());
        }        
    }
    
    private void doljInlagg(String titel)
    {
        String sqlFraga = "Update inlagg set inlagg.visible = 'false' where inlagg.titel = '" + titel + "';";
        System.out.println(sqlFraga);
        try
        {
            idb.update(sqlFraga);
        }
        catch(InfException e)
        {
            System.out.println(e.getMessage());
        }
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabPanelAmnen = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPaneSocialt = new javax.swing.JTextPane();
        jtabPaneForsk = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneForsk = new javax.swing.JTextPane();
        tabPaneUtb = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneUtbildning = new javax.swing.JTextPane();
        btnDoljInlagg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabPanelAmnen.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabPanelAmnen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabPanelAmnen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTabPanelAmnen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabPanelAmnenStateChanged(evt);
            }
        });

        txtPaneSocialt.setEditable(false);
        jScrollPane2.setViewportView(txtPaneSocialt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabPanelAmnen.addTab("Socialt", jPanel1);

        jTextPaneForsk.setEditable(false);
        jScrollPane1.setViewportView(jTextPaneForsk);

        javax.swing.GroupLayout jtabPaneForskLayout = new javax.swing.GroupLayout(jtabPaneForsk);
        jtabPaneForsk.setLayout(jtabPaneForskLayout);
        jtabPaneForskLayout.setHorizontalGroup(
            jtabPaneForskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtabPaneForskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        jtabPaneForskLayout.setVerticalGroup(
            jtabPaneForskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtabPaneForskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabPanelAmnen.addTab("Forskning", jtabPaneForsk);

        jTextPaneUtbildning.setEditable(false);
        jScrollPane3.setViewportView(jTextPaneUtbildning);

        javax.swing.GroupLayout tabPaneUtbLayout = new javax.swing.GroupLayout(tabPaneUtb);
        tabPaneUtb.setLayout(tabPaneUtbLayout);
        tabPaneUtbLayout.setHorizontalGroup(
            tabPaneUtbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneUtbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabPaneUtbLayout.setVerticalGroup(
            tabPaneUtbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneUtbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabPanelAmnen.addTab("Utbildning", tabPaneUtb);

        btnDoljInlagg.setText("Dölj markerat inlägg");
        btnDoljInlagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoljInlaggMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabPanelAmnen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDoljInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnDoljInlagg)
                .addGap(18, 18, 18)
                .addComponent(jTabPanelAmnen, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }
    

    public void refreshList() {

    }//GEN-LAST:event_formWindowOpened
  
    
    public void showSocInlagg(String amne1){
       if(amne1 == null){
           amne1 = "Socialt";
           StyledDocument docSoc = txtPaneSocialt.getStyledDocument();
           inlagg.emptyInlaggPane(docSoc);
           inlagg.showSocInlagg1(docSoc, amne1);
       }
       if(amne1.equals("Socialt")){
           
           StyledDocument docSoc = txtPaneSocialt.getStyledDocument();
           inlagg.emptyInlaggPane(docSoc);
           inlagg.showSocInlagg1(docSoc, amne1);
       }
       if(amne1.equals("Forskning")){
           
           StyledDocument docForsk = jTextPaneForsk.getStyledDocument();  
           inlagg.emptyInlaggPane(docForsk);
           inlagg.showSocInlagg1(docForsk, amne1);
       }
       if(amne1.equals("Utbildning")){
       
           StyledDocument docUtb = jTextPaneUtbildning.getStyledDocument();
           inlagg.emptyInlaggPane(docUtb);
           inlagg.showSocInlagg1(docUtb, amne1);
       }
       }
   
    
    private void jTabPanelAmnenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabPanelAmnenStateChanged
        String a = jTabPanelAmnen.getTitleAt(jTabPanelAmnen.getSelectedIndex());
        System.out.println(a);
        String b = "Forskning";
        String c = "Utbildning";
        String d = "Socialt";
        
        if(a.equals(b)){
            
            showSocInlagg(a);
            showSocInlagg(d);
            
        }
        if(a.equals(c)){
            showSocInlagg(a);
             showSocInlagg(d);
            
        }
    }//GEN-LAST:event_jTabPanelAmnenStateChanged

    private void btnDoljInlaggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoljInlaggMouseClicked
        getSelectedTextOchDolj();
    }//GEN-LAST:event_btnDoljInlaggMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inlagg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InlaggAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoljInlagg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabPanelAmnen;
    private javax.swing.JTextPane jTextPaneForsk;
    private javax.swing.JTextPane jTextPaneUtbildning;
    private javax.swing.JPanel jtabPaneForsk;
    private javax.swing.JPanel tabPaneUtb;
    private javax.swing.JTextPane txtPaneSocialt;
    // End of variables declaration//GEN-END:variables
}
