/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informatikb_system;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Oliver
 */
public class Inloggningsruta extends javax.swing.JFrame {

    private Anvandare user;
    
    public Inloggningsruta() {
        initComponents();
        setLocationRelativeTo(null);
        tfUsername.setText("");
        user = new Anvandare();
        getContentPane().setBackground(Color.white);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggning = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField();
        tfUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        lblInloggning.setBackground(java.awt.SystemColor.activeCaption);
        lblInloggning.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        lblInloggning.setForeground(new java.awt.Color(0, 0, 0));
        lblInloggning.setText("Inloggning");
        getContentPane().add(lblInloggning);
        lblInloggning.setBounds(380, 50, 188, 49);

        pfPassword.setText("jPasswordField1");
        pfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPasswordFocusGained(evt);
            }
        });
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(pfPassword);
        pfPassword.setBounds(370, 260, 225, 28);

        tfUsername.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfUsername);
        tfUsername.setBounds(370, 170, 225, 28);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Användarnamn");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 130, 175, 33);

        btnLogIn.setText("Logga in");
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogInMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogIn);
        btnLogIn.setBounds(440, 320, 120, 40);

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setLabelFor(pfPassword);
        jLabel2.setText("Lösenord");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 220, 105, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informatikb_system/Icons/orebro_370x370.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 370, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseClicked
        String losenord = pfPassword.getText();
        String username = tfUsername.getText();
        
        boolean valid = user.valideraInloggning(username, losenord);
        if(valid)
        {
            String aID = user.getAID();
            Inlagg inlaggruta = new Inlagg(aID);
            inlaggruta.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Du har skrivit in fel användarnamn eller lösenord.");
        }
        
        
    }//GEN-LAST:event_btnLogInMouseClicked

    private void pfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusGained
        pfPassword.setText("");
    }//GEN-LAST:event_pfPasswordFocusGained

    private void pfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String losenord = pfPassword.getText();
            String username = tfUsername.getText();
        
            boolean valid = user.valideraInloggning(username, losenord);
            if(valid)
            {
                String aID = user.getAID();
                Inlagg inlaggruta = new Inlagg(aID);
                inlaggruta.setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Du har skrivit in fel användarnamn eller lösenord.");
            }
        }
    }//GEN-LAST:event_pfPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggningsruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggningsruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggningsruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggningsruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inloggningsruta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblInloggning;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
