/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informatikb_system;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author Maximilian
 */
public class MotesInfo extends javax.swing.JFrame {
    
    private Databas db;
    private HashMap<String, String> info;
    private static String mID;
    private static String aid;
    private boolean anmald;

    /**
     * Creates new form MotesInfo
     */
    public MotesInfo(String mid, String aid) {
        mID = mid;
        this.aid = aid;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
        db = new Databas();
        hamtaMotesInfo(mID);
        fillMotesInfo();
        fillDeltagare();
        fillInbjudna();
        anmald = db.anmaldTillMote(aid, mID);
        setAnmalKnapp();
        
    }
    /*
    * Metod för att hämta info om valt möte
    */
    public void fillMotesInfo()
    {
        String aid = info.get("ANSVARIG");
        String namn = db.hamtaAnstalldNamn(aid);
        lblAnsvarig.setText(namn);
        lblTitel.setText(info.get("TITEL"));
        lblDatum.setText(info.get("DATUM"));
        lblStarttid1.setText(info.get("START_TID"));
        lblSluttid1.setText(info.get("SLUT_TID"));
        lblPlats1.setText(info.get("SAL"));
        taBeskrivning.setText(info.get("BESKRIVNING"));
    }
    
    /*
    * Hämtar info för det valda mötet och sparar lokalt i objektet
    */
    public void hamtaMotesInfo(String mID)
    {
        info = db.hamtaMotesInfo(mID);
    }
    
    /*
    * Fyller listan med namn på deltagande för möte
    */
    public void fillDeltagare()
    {
        String kebab = "Det finns inga anställda som är anmälda till detta möte än";
        ArrayList<String> deltagande = db.hamtaAnstalldaMote(mID);
        DefaultListModel listModel = new DefaultListModel();
        listDeltagare.setModel(listModel);
        if(deltagande.isEmpty())
        {
            listModel.addElement(kebab);
        }
        else
        {
        for(String deltagare : deltagande)
        {
            
            listModel.addElement(deltagare);
        }
        }
    }
    
    public void fillInbjudna()
    {
        ArrayList<String> inbjudna = new ArrayList<String>();
        inbjudna = db.hamtaInbjudnaAnstallda(mID);
        DefaultListModel listModel = new DefaultListModel();
        listInbjudna.setModel(listModel);
        for(String inbjuden : inbjudna)
        {
            
            listModel.addElement(inbjuden);
        }
    }
    
    public void anmalTillMote()
    {
        if(anmald)
        {
            db.avanmalAnstalldMote(aid, mID);
            JOptionPane.showMessageDialog(this, "Du är nu avanmäld till mötet");
            anmald = false;
        }
        else
        {
            db.anmalAnstalldTillMote(aid, mID);
            JOptionPane.showMessageDialog(this, "Du är nu anmäld till mötet");
            anmald = true;
        }
        fillDeltagare();
        fillInbjudna();
        setAnmalKnapp();
    }
    
    public void setAnmalKnapp()
    {
        if(anmald)
        {
            btnAnmal.setText("Avanmäl");
        }
        else
        {
            btnAnmal.setText("Anmäl");
        }
    }

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStarttid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBeskrivning = new javax.swing.JTextArea();
        lblSluttid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDeltagare = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDeltagare = new javax.swing.JList<>();
        lblTitel = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblStarttid1 = new javax.swing.JLabel();
        lblSluttid1 = new javax.swing.JLabel();
        lblPlats1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAnsvarig = new javax.swing.JLabel();
        btnAnmal = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listInbjudna = new javax.swing.JList<>();
        lblInbjudna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblStarttid.setText("Starttid:");

        jLabel3.setText("Plats:");

        jLabel4.setText("Beskrivning:");

        taBeskrivning.setEditable(false);
        taBeskrivning.setColumns(20);
        taBeskrivning.setRows(5);
        jScrollPane1.setViewportView(taBeskrivning);

        lblSluttid.setText("Sluttid:");

        jLabel1.setText("Datum:");

        lblDeltagare.setText("Deltagare:");

        jScrollPane2.setViewportView(listDeltagare);

        lblTitel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblTitel.setText("Titel");

        lblDatum.setText("DATUM");

        lblStarttid1.setText("STARTTID");

        lblSluttid1.setText("SLUTTID");

        lblPlats1.setText("PLATS");

        jLabel2.setText("Ansvarig:");

        lblAnsvarig.setText("ANSVARIG");

        btnAnmal.setText("Anmäl");
        btnAnmal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnmalMouseClicked(evt);
            }
        });

        jScrollPane4.setViewportView(listInbjudna);

        lblInbjudna.setText("Inbjudna:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnmal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(lblSluttid)
                                    .addComponent(lblStarttid)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatum)
                                    .addComponent(lblStarttid1)
                                    .addComponent(lblPlats1)
                                    .addComponent(lblAnsvarig)
                                    .addComponent(lblSluttid1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeltagare)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInbjudna, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitel)
                    .addComponent(lblDeltagare)
                    .addComponent(lblInbjudna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblAnsvarig))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblDatum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStarttid)
                            .addComponent(lblStarttid1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSluttid)
                            .addComponent(lblSluttid1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblPlats1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnmal)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnmalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnmalMouseClicked
       anmalTillMote();
    }//GEN-LAST:event_btnAnmalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotesInfo(mID, aid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnmal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAnsvarig;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDeltagare;
    private javax.swing.JLabel lblInbjudna;
    private javax.swing.JLabel lblPlats1;
    private javax.swing.JLabel lblSluttid;
    private javax.swing.JLabel lblSluttid1;
    private javax.swing.JLabel lblStarttid;
    private javax.swing.JLabel lblStarttid1;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JList<String> listDeltagare;
    private javax.swing.JList<String> listInbjudna;
    private javax.swing.JTextArea taBeskrivning;
    // End of variables declaration//GEN-END:variables
}
