/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informatikb_system;

import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileFilter;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Oliver
 */
public class SkrivaInlaggTest extends javax.swing.JFrame {

    private static String aid;
    private InlaggMgt mgt;
    private Calendar cal;
    private static Inlagg inlaggRuta;
    private InfDB idb;
    private String filePath;
    private JFileChooser fileChooser;
    private String copiedFilePath;

    /**
     * Creates new form SkrivaInlagg
     */
    public SkrivaInlaggTest(String aid, Inlagg inlaggRuta) {
        anslutDatabas();
        initComponents();
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.aid = aid;
        System.out.println(aid);
        mgt = new InlaggMgt();
        this.inlaggRuta = inlaggRuta;
    }

    private void anslutDatabas() {
        try {
            String path = System.getProperty("user.dir"); //Hämtar user direcotry
            idb = new InfDB(path + "/databas/DATABASE.FDB");
            System.out.println("Uppkopplingen lyckades");
        } catch (InfException e) {
            System.out.println(e.getMessage());
        }
    }

    public void laggTillBloggInlagg(String titel, String text, String aid, String amne, String sokvag) {
        String date = LocalDateTime.now().toString();
        String date2 = date.substring(0, 10);
        String time = date.substring(11, 19);
        System.out.println(date2 + " Tid: " + time);
        String visible = "true";
        try {
            String iid = idb.getAutoIncrement("INLAGG", "IID");
            String sqlFraga = "INSERT INTO INLAGG "
                    + "VALUES(" + iid + ",'" + titel + "', '" + date2 + "', '" + time + "', '" + visible + "', " + aid + ", '" + text + "', '" + amne + "', '" + sokvag + "');";
            System.err.println(sqlFraga);
            idb.insert(sqlFraga);

        } catch (InfException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Ooops something went wrong! Dont use symbol ' for now :)");
            return;
        }

    }
    
    private String getFilvag()
    {
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBloggInlagg = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnPostaInlagg = new javax.swing.JButton();
        tfTitel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxAmnen = new javax.swing.JComboBox<>();
        btnBifogaFil = new javax.swing.JButton();
        lblBild = new javax.swing.JLabel();

        FileChooser.setDialogTitle("my open dialog box");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "exempel kategori", "exempel kategori", "exempel kategori", "exempel kategori" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Kategori:");

        taBloggInlagg.setColumns(20);
        taBloggInlagg.setRows(5);
        jScrollPane1.setViewportView(taBloggInlagg);

        jCheckBox1.setText("Markera som viktigt");

        btnPostaInlagg.setText("Posta inlägg");
        btnPostaInlagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPostaInlaggMouseClicked(evt);
            }
        });

        jLabel3.setText("Titel");

        cbxAmnen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Socialt", "Forskning", "Utbildning" }));
        cbxAmnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAmnenActionPerformed(evt);
            }
        });

        btnBifogaFil.setText("Bifoga fil");
        btnBifogaFil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBifogaFilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnPostaInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBifogaFil, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxAmnen, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3)
                                .addGap(454, 454, 454)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jCheckBox1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBild, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel2)
                            .addComponent(cbxAmnen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPostaInlagg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBifogaFil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostaInlaggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostaInlaggMouseClicked

        String text = taBloggInlagg.getText();
        int count = text.length();
        String titel = tfTitel.getText();
        int titelCount = titel.length();
        String sokvag = copiedFilePath;
        if(sokvag == null)
        {
            sokvag = "Ingen fil";
        }
        if (titelCount > 50) {
            JOptionPane.showMessageDialog(this, "Vad är då för titel så long som över 50 tecken??? Korta ner lite!!");
            return;
        } else if (count > 1000) {
            JOptionPane.showMessageDialog(this, "Max 1000 tillåtna tecken i ett inlägg!");
            return;
        } else {
            String amne = cbxAmnen.getSelectedItem().toString();
            laggTillBloggInlagg(titel, text, aid, amne, sokvag);
            inlaggRuta.showSocInlagg(amne);
            dispose();
            JOptionPane.showMessageDialog(this, "Grattis, du har postat ett nytt inlägg!");
        }
    }//GEN-LAST:event_btnPostaInlaggMouseClicked


    private void cbxAmnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAmnenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAmnenActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnBifogaFilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBifogaFilMouseClicked

        JFileChooser fileChooser = new JFileChooser();
        int res = fileChooser.showOpenDialog(SkrivaInlaggTest.this);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        if (res == JFileChooser.APPROVE_OPTION) {

            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            String fileName = selectedFile.getName();
            String userDirectory = System.getProperty("user.dir");
            String stringPath = userDirectory + "/databas/Bifogade_Filer/";
            Path path1 = Paths.get(path);
            Path path2 = Paths.get(stringPath);
            try {
                Files.copy(path1, path2.resolve(path1.getFileName()), StandardCopyOption.REPLACE_EXISTING);
                copiedFilePath = fileName;
                
                lblBild.setIcon(ReziseImage(path));
                
            } catch (Exception e) {
                System.out.println(e.getMessage());
            
        } }else {
            System.out.println("No file was selected.");
        }
        
    }
   
        
    public ImageIcon ReziseImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblBild.getWidth(), lblBild.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;


    }//GEN-LAST:event_btnBifogaFilMouseClicked
    public void saveFilePath(String path) {
        String sqlFraga = "ALTER INLAGG SET FILPATH = " + path + " WHERE AID = " + aid;
        System.out.print(sqlFraga);
        try {
            idb.update(sqlFraga);

        } catch (InfException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkrivaInlaggTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkrivaInlaggTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkrivaInlaggTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkrivaInlaggTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkrivaInlaggTest(aid, inlaggRuta).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JButton btnBifogaFil;
    private javax.swing.JButton btnPostaInlagg;
    private javax.swing.JComboBox<String> cbxAmnen;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBild;
    private javax.swing.JTextArea taBloggInlagg;
    private javax.swing.JTextField tfTitel;
    // End of variables declaration//GEN-END:variables

}
